# Generated by Django 2.2.3 on 2019-12-04 17:26

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='LDAP ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Last name')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=40, verbose_name='Course Name')),
                ('course_details', models.CharField(blank=True, max_length=1000, verbose_name='Course Details')),
                ('eligibility_criteria', models.CharField(blank=True, max_length=500, verbose_name='Eligibility')),
                ('department', models.CharField(choices=[('CS', 'CS'), ('EE', 'EE'), ('EP', 'EP')], max_length=50, verbose_name='Department')),
                ('deadline', models.DateField(default=datetime.date(2019, 12, 11))),
                ('duration', models.CharField(choices=[('Full Semester', 'Full Semester'), ('Half Semester', 'Half Semester')], default='Full Semester', max_length=10)),
                ('extra_questions', models.CharField(max_length=1500)),
                ('year', models.IntegerField()),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Autumn'), (2, 'Spring'), (3, 'Summer')])),
            ],
        ),
        migrations.CreateModel(
            name='FacultyUser',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('department', models.CharField(choices=[('CS', 'CS'), ('EE', 'EE'), ('EP', 'EP')], max_length=50, verbose_name='Department')),
            ],
            options={
                'db_table': 'Faculty Users',
            },
            bases=('student_faculty.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpi', models.FloatField(verbose_name='CPI')),
                ('year_of_study', models.CharField(max_length=1, verbose_name='Year Of Study')),
                ('department', models.CharField(choices=[('CS', 'CS'), ('EE', 'EE'), ('EP', 'EP')], max_length=50, verbose_name='Department')),
                ('contact_no', models.CharField(max_length=12, verbose_name='Phone')),
                ('selected_yet', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Student Users',
            },
            bases=('student_faculty.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Field1- Replace with actual parameter')),
                ('field2', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Field2')),
                ('field3', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Field3')),
                ('comments', models.CharField(max_length=1000, verbose_name='Comments')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback_course', to='student_faculty.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback_student', to='student_faculty.StudentUser')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Field1- Replace with actual parameter')),
                ('field2', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Field2')),
                ('field3', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Field3')),
                ('comments', models.CharField(max_length=1000, verbose_name='Comments')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_feedback_course', to='student_faculty.Course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_faculty.FacultyUser')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_feedback_student', to='student_faculty.StudentUser')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='profs',
            field=models.ManyToManyField(to='student_faculty.FacultyUser'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Waitlist', 'Waitlist'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], default='On Hold', max_length=100)),
                ('grade', models.CharField(max_length=2, verbose_name='Grade')),
                ('answers_to_questions', models.CharField(max_length=6000, verbose_name='Answers')),
                ('waitlist_num', models.IntegerField(verbose_name='Waitlist Number')),
                ('created_or_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_faculty.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_faculty.StudentUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_name', 'year', 'semester')},
        ),
    ]
